const swaggerAutogen = require('swagger-autogen')();

const doc = {
  info: {
    title: 'Automated Campus Event Management API',
    description: 'This API documentation was automatically generated by scanning Express routes.',
    version: '1.0.0'
  },
  host: 'https://cse341-wd-1.onrender.com',
    schemes: ['http', 'https'],
        // Define structural schemas for auto-documentation mapping
    definitions: {
        VenueInput: {
            $name: "Main Auditorium",
            $building: "Administration Block",
            $capacity: 600,
            hasProjector: true
        },
        VenueResponse: {
            _id: "651c2f9b8b3f4a123456789a",
            name: "Main Auditorium",
            building: "Administration Block",
            capacity: 600,
            hasProjector: true,
            createdAt: "2026-09-26T17:00:00.000Z",
            updatedAt: "2026-09-26T17:00:00.000Z"
    
        },
        // --- 8-Field Event Definitions ---
        EventInput: {
            $title: "Annual Hackathon 2026",
            $description: "A 48-hour challenge to build innovative software solutions.",
            $date: "2026-10-15T09:00:00.000Z",
            $organizer: "Computer Science Society",
            $venueId: "651c2f9b8b3f4a123456789a",
            $capacity: 150,
            isPublished: true,
            tags: ["tech", "coding", "competition"]
        },
        EventResponse: {
            _id: "651c3a7f8b3f4a123456789e",
            title: "Annual Hackathon 2026",
            description: "A 48-hour challenge to build innovative software solutions.",
            date: "2026-10-15T09:00:00.000Z",
            organizer: "Computer Science Society",
            venueId: {
                _id: "651c2f9b8b3f4a123456789a",
                name: "Main Auditorium",
                building: "Administration Block"
            },
            capacity: 150,
            isPublished: true,
            tags: ["tech", "coding", "competition"],
            createdAt: "2026-09-26T17:00:00.000Z",
            updatedAt: "2026-09-26T17:00:00.000Z"
        }
    }
};

const outputFile = './swagger-output.json';
const routesFiles = ['./app.js']; // Point this to your main entry file where routes are mounted

// Generate the documentation file
swaggerAutogen(outputFile, routesFiles, doc);
