const swaggerAutogen = require('swagger-autogen')();
const dotenv = require('dotenv');

// Load environment variables so the script can see them during builds
dotenv.config();

// Determine if we are running in production or locally
const isProduction = process.env.NODE_ENV === 'production';

// Dynamic host binding
const HOST = isProduction ? 'cse341-wd-1.onrender.com' : 'localhost:8081';
const SCHEMES = isProduction ? 'https' : 'http';
const BASE_URL = isProduction ? `https://${HOST}` : `http://${HOST}`;

// Swagger documentation configuration
const doc = {
  info: {
    title: 'Automated Campus Event Management API',
    description: 'This API documentation was automatically generated by scanning Express routes.',
    version: '1.0.0'
  },
  host: HOST,
  basePath: '/',
  schemes: SCHEMES,

  // 🔐 Securely bind the URLs for Google OAuth
  securityDefinitions: {
    googleOAuth: {
      type: 'oauth2',
      flow: 'accessCode',
      authorizationUrl: `${BASE_URL}/auth/google`, // Dynamically switches between http and https
      tokenUrl: `${BASE_URL}/auth/google/callback`, // Dynamically switches between http and https
        scopes: {
        profile: 'Access your basic profile information',
        email: 'Access your email address'
      },
    },
  },

  definitions: {
    VenueInput: {
      $name: 'Main Auditorium',
      $building: 'Administration Block',
      $capacity: 600,
      hasProjector: true
    },
    VenueResponse: {
      _id: '651c2f9b8b3f4a123456789a',
      name: 'Main Auditorium',
      building: 'Administration Block',
      capacity: 600,
      hasProjector: true
    },
    EventInput: {
      $title: 'Annual Hackathon 2026',
      $description: 'A 48-hour challenge to build innovative software solutions.',
      $date: '2026-10-15T09:00:00.000Z',
      $organizer: 'Computer Science Society',
      $venueId: '651c2f9b8b3f4a123456789a',
      $capacity: 150,
      isPublished: true,
      tags: ['tech', 'coding', 'competition']
    },
    EventResponse: {
      _id: '651c3a7f8b3f4a123456789e',
      title: 'Annual Hackathon 2026',
      description: 'A 48-hour challenge to build innovative software solutions.',
      date: '2026-10-15T09:00:00.000Z',
      organizer: 'Computer Science Society',
      venueId: {
        _id: '651c2f9b8b3f4a123456789a',
        name: 'Main Auditorium',
        building: 'Administration Block'
      },
      capacity: 150,
      isPublished: true,
      tags: ['tech', 'coding', 'competition'],
      createdAt: '2026-09-26T17:00:00.000Z',
      updatedAt: '2026-09-26T17:00:00.000Z'
    }
  }
};

const outputFile = './swagger-output.json';
const routesFiles = ['./app.js'];

swaggerAutogen(outputFile, routesFiles, doc);
